TripPlanner: Database Class Reference
Database Class Reference
#include <Database.h>
Public Member Functions
Database ()
void run (std::string start, std::string end, std::string option, int algorithm)
Detailed Description
Class responsible for generating a graph and running the algorithms.
Definition at line 14 of file Database.h.
Constructor & Destructor Documentation
Database()
Database::Database () inline
Creates an instance of Database.
Definition at line 75 of file Database.h.
References run().
Member Function Documentation
run()
void Database::run (std::string start, std::string end, std::string option, int algorithm)
Runs the algorithm specified by the user.
Parameters
start Starting stop.
end Destination stop.
option Criteria used for best path.
algorithm Algorithm the user wants to run.
Definition at line 25 of file Database.cpp.
References Stop::getZone(), and utils::haversineDistance().
Referenced by Database().
The documentation for this class was generated from the following files:
Database.h
Database.cpp