TripPlanner: Loader Class Reference
Loader Class Reference
#include <Loader.h>
Public Member Functions
Loader ()
void run ()
Friends
class Database
Detailed Description
Class responsible for loading the information regarding stops and lines.
Definition at line 20 of file Loader.h.
Constructor & Destructor Documentation
Loader()
Loader::Loader ()
Creates an instance of Loader.
Definition at line 8 of file Loader.cpp.
Member Function Documentation
run()
void Loader::run ()
Runs the loader.
Definition at line 12 of file Loader.cpp.
References utils::calcLineString(), utils::calcMultiLineString(), utils::GET(), Stop::getCode(), Line::getCode(), and utils::isEmpty().
The documentation for this class was generated from the following files:
Loader.h
Loader.cpp