#ifndef TRIP_PLANNER_GRAPHFWD_H
#define TRIP_PLANNER_GRAPHFWD_H

#include <string>
#include <vector>

namespace trip_planner {

	template <class T> class vertex;
	template <class T> class edge;
	template <class T> class graph;
	template <class T> class mutable_priority_queue;

	/** Path generated by the algorithms. */
	template <class T>
	using path_t = std::pair<std::vector<T>, std::vector<std::string>>;
}

#endif