TripPlanner: utils Namespace Reference
utils Namespace Reference
Functions
nlohmann::json GET (std::string url)
double haversineDistance (const coord_t p1, const coord_t p2)
double degToRad (const double deg)
bool isEmpty (std::string file)
double calcLineString (linestring_t line)
double calcMultiLineString (multilinestring_t multiline)
Detailed Description
Utility functions.
Function Documentation
calcLineString()
double utils::calcLineString (linestring_t line)
Calculates the distance of a LineString.
Parameters
line LineString to be measured.
Returns
Distance of the LineString.
Definition at line 44 of file Utils.cpp.
References haversineDistance().
Referenced by calcMultiLineString(), and Loader::run().
calcMultiLineString()
double utils::calcMultiLineString (multilinestring_t multiline)
Calculates the distance of a MultiLineString.
Parameters
multiline MultiLineString to be measured.
Returns
Distance of MultiLineString.
Definition at line 59 of file Utils.cpp.
References calcLineString().
Referenced by Loader::run().
degToRad()
double utils::degToRad (const double deg)
Converts degrees to radians.
Parameters
deg Degrees to be converted.
Returns
Degrees converted to radians.
Definition at line 34 of file Utils.cpp.
References isEmpty().
Referenced by haversineDistance().
GET()
nlohmann::json utils::GET (std::string url)
Makes a GET request to a given URL.
Parameters
url URL of the API.
Referenced by Loader::run().
haversineDistance()
double utils::haversineDistance (const coord_t p1, const coord_t p2)
Algorithm to calculate distance between two points, using its coordinates.
Parameters
p1 Coordinates of starting point.
p2 Coordinates of destination point
Returns
Distance between the points.
Definition at line 20 of file Utils.cpp.
References degToRad().
Referenced by calcLineString(), and Database::run().
isEmpty()
bool utils::isEmpty (std::string file)
Checks if a file is empty.
Parameters
file File to be checked.
Returns
True if the file is empty, false otherwise.
Referenced by degToRad(), and Loader::run().